### ISSUE TITLE
Authentication failed "saml_token_provider"

### ISSUE THREAD

**Issue by MousePolice** [iamlu-coding/python-sharepoint-office365-api#5]
Using the download_files.py from the repo, appear to have an authentication failure. I am using this on my work account. I have not been able to find any documentation on the office 365 api to help debug the issue. Appears to be an error with "saml provider". If you have any suggestions please do advise. Thank you.

Observed behavior
the download script appears to fail at the authentication stage.

**Expected behavior**
the download script completes the authentication and downloads specified file

Error log
`Traceback (most recent call last):
  File "\python-sharepoint-office365-api\examples\download_files.py", line 41, in <module>
    get_files_by_pattern(FILE_NAME_PATTERN, FOLDER_NAME)
  File "\python-sharepoint-office365-api\examples\download_files.py", line 32, in get_files_by_pattern
    files_list = SharePoint()._get_files_list(folder)
  File "\python-sharepoint-office365-api\examples\office365_api.py", line 31, in _get_files_list
    root_folder.expand(["Files", "Folders"]).get().execute_query()
  File "\Environments\env_office\lib\site-packages\office365\runtime\client_object.py", line 44, in execute_query
    self.context.execute_query()
  File "\Environments\env_office\lib\site-packages\office365\runtime\client_runtime_context.py", line 181, in execute_query
    self.pending_request().execute_query(qry)
  File "\Environments\env_office\lib\site-packages\office365\runtime\client_request.py", line 57, in execute_query
    response = self.execute_request_direct(request)
  File "\Environments\env_office\lib\site-packages\office365\runtime\client_request.py", line 69, in execute_request_direct
    self.beforeExecute.notify(request)
  File "\Environments\env_office\lib\site-packages\office365\runtime\types\event_handler.py", line 21, in notify
    listener(*args, **kwargs)
  File "\Environments\env_office\lib\site-packages\office365\sharepoint\client_context.py", line 212, in _authenticate_request
    self.authentication_context.authenticate_request(request)
  File "\Environments\env_office\lib\site-packages\office365\runtime\auth\authentication_context.py", line 97, in authenticate_request
    self._provider.authenticate_request(request)
  File "\Environments\env_office\lib\site-packages\office365\runtime\auth\providers\saml_token_provider.py", line 77, in authenticate_request
    self.ensure_authentication_cookie()
  File "\Environments\env_office\lib\site-packages\office365\runtime\auth\providers\saml_token_provider.py", line 84, in ensure_authentication_cookie
    self._cached_auth_cookies = self.get_authentication_cookie()
  File "\Environments\env_office\lib\site-packages\office365\runtime\auth\providers\saml_token_provider.py", line 97, in get_authentication_cookie
    token = self._acquire_service_token_from_adfs(user_realm.STSAuthUrl)
  File "\Environments\env_office\lib\site-packages\office365\runtime\auth\providers\saml_token_provider.py", line 140, in _acquire_service_token_from_adfs
    assertion_node = dom.getElementsByTagNameNS("urn:oasis:names:tc:SAML:1.0:assertion", 'Assertion')[0].toxml()
IndexError: list index out of range`

**Comment by MousePolice** [comment]
Issue is resolved. My bad. Password typo. Sorry.
